### ISSUE TITLE
Use heroku cache

### ISSUE THREAD

**Issue by joshRpowell** [sheck/heroku-buildpack-zbar#10]
See example

https://github.com/gaffneyc/heroku-buildpack-jemalloc/commit/c019bcd6b751f0e861a556bcd40590592201db25

**Comment by sheck** [comment]
Yea that's [something I've wanted to do](https://github.com/sheck/heroku-buildpack-zbar/commit/0639b97d91d20e9905d624d6191ae4f54dd3f634#diff-04c6e90faac2675aa89e2176d2eec7d8R25) for a while now. I'm not still using this buildpack regularly, do you want to work on a PR for this?

**Comment by joshRpowell** [comment]
hi @sheck sure thing. still in one of my production apps, but working on much either.

will find some time in the near future.
